import { useEffect, useMemo, useState } from "react"
import { Activity, AudioLines, Camera, ChevronRight, CircleAlert, Gauge, LayoutDashboard, Radio, RotateCcw, Settings2, ShieldAlert, Video } from "lucide-react"
import { Button } from "@/components/ui/button"
import { DeterministicStudioAdapter, type CameraControl, type CameraState, type CommandState, type Health, type StudioAdapter, useStudio } from "@/studio-adapter"

type Route="dashboard"|"cameras"|"audio"|"studio"
const routes: {id:Route;label:string;icon:typeof Camera}[]=[{id:"dashboard",label:"Dashboard",icon:LayoutDashboard},{id:"cameras",label:"Cameras",icon:Camera},{id:"audio",label:"Audio",icon:AudioLines},{id:"studio",label:"Studio",icon:Video}]
const healthLabel:Record<Health,string>={ready:"Ready",warning:"Attention",offline:"Offline"}
const stateLabel:Record<CommandState,string>={confirmed:"Confirmed",pending:"Pending",rejected:"Rejected",unsupported:"Unsupported",conflict:"Conflict","reconnect-required":"Reconnect required"}

function Status({value,label}:{value:Health;label?:string}){return <span className={`status status-${value}`}><i aria-hidden="true"/>{label??healthLabel[value]}</span>}
function Feed({camera,compact=false}:{camera:CameraState;compact?:boolean}){return <div className={`feed ${camera.tally} ${compact?"compact":""}`} style={{background:camera.frame}} aria-label={`${camera.name}, ${camera.tally}, ${healthLabel[camera.health]}`}><div className="feed-grid"/><div className="feed-top"><span>{camera.name}</span><Status value={camera.health}/></div>{camera.heldFrame?<div className="held"><ShieldAlert/> LAST FRAME HELD</div>:null}<div className="feed-bottom"><span>{camera.model}</span><span>{camera.latencyMs} ms</span></div></div>}
function AlertRail({alerts,onGo}:{alerts:ReturnType<typeof useStudio>["alerts"];onGo:(route:Route)=>void}){return <div className="alert-rail" aria-live="assertive">{alerts.map(a=><button key={a.id} className={`alert ${a.severity}`} onClick={()=>onGo(a.destination.slice(1) as Route)}><CircleAlert/><span><strong>{a.title}</strong><small>{a.detail}</small></span><ChevronRight/></button>)}</div>}

function Dashboard({state,onGo}:{state:ReturnType<typeof useStudio>;onGo:(r:Route)=>void}){const program=state.cameras.find(c=>c.id===state.programId)!;const preview=state.cameras.find(c=>c.id===state.previewId)!;return <main><Header title="Dashboard" subtitle="System readiness and live production overview"/><section className="readiness">{Object.entries(state.readiness).map(([k,v])=><button key={k} className="metric" onClick={()=>onGo(k==="phones"?"cameras":"studio")}><span>{k==="virtualCamera"?"Virtual camera":k==="obs"?"OBS adapter":k[0].toUpperCase()+k.slice(1)}</span><Status value={v}/><strong>{v==="ready"?"Operational":v==="warning"?"Needs review":"Unavailable"}</strong></button>)}</section><AlertRail alerts={state.alerts} onGo={onGo}/><section className="two-col"><Panel title="Live switcher" action="Open Studio" onAction={()=>onGo("studio")}><div className="dual-feed"><div><label>PROGRAM</label><Feed camera={program}/></div><div><label>PREVIEW</label><Feed camera={preview}/></div></div></Panel><Panel title="Camera health" action="Manage" onAction={()=>onGo("cameras")}><div className="health-list">{state.cameras.map(c=><button key={c.id} onClick={()=>onGo("cameras")}><Status value={c.health}/><span><b>{c.name}</b><small>{c.signal}% signal · {c.latencyMs} ms · {c.battery}% battery</small></span><span>{c.thermal}</span></button>)}</div></Panel></section><section className="two-col"><Panel title="Program audio" action="Open Audio" onAction={()=>onGo("audio")}><div className="audio-summary">{state.audio.filter(a=>a.routed).map(a=><div key={a.id}><AudioLines/><span><b>{a.name}</b><small>Explicitly routed · {a.syncMs>0?"+":""}{a.syncMs} ms</small></span><Meter level={a.level}/></div>)}</div></Panel><Panel title="Output safety"><div className="output-grid"><div><Radio/><span>ISO recording</span><strong>{state.output.recording?"Recording":"Stopped"}</strong></div><div><CircleAlert/><span>Declared gaps</span><strong>{state.output.gapCount}</strong></div><div><Gauge/><span>Worst latency</span><strong>{Math.max(...state.cameras.map(c=>c.latencyMs))} ms</strong></div></div></Panel></section></main>}
function Panel({title,action,onAction,children}:{title:string;action?:string;onAction?:()=>void;children:React.ReactNode}){return <section className="panel"><header><h2>{title}</h2>{action?<Button variant="ghost" size="sm" onClick={onAction}>{action}<ChevronRight/></Button>:null}</header>{children}</section>}
function Header({title,subtitle,actions}:{title:string;subtitle:string;actions?:React.ReactNode}){return <header className="page-header"><div><h1>{title}</h1><p>{subtitle}</p></div>{actions}</header>}
function Meter({level}:{level:number}){const pct=Math.max(4,Math.min(100,(level+60)*1.7));return <div className="meter" role="meter" aria-label={`Audio level ${level} decibels`} aria-valuenow={level} aria-valuemin={-60} aria-valuemax={0}><i style={{width:`${pct}%`}}/></div>}

function Cameras({state,adapter}:{state:ReturnType<typeof useStudio>;adapter:StudioAdapter}){const [selected,setSelected]=useState(state.cameras[0].id);const camera=state.cameras.find(c=>c.id===selected)!;const labels:Record<CameraControl,string>={lens:"Lens",zoom:"Zoom",iso:"ISO",shutter:"Shutter",whiteBalance:"White balance",focus:"Focus",torch:"Torch",stabilization:"Stabilization"};return <main><Header title="Cameras" subtitle="Connected phones and authoritative camera controls"/><div className="camera-layout"><section className="camera-grid" aria-label="Connected phones">{state.cameras.map(c=><button key={c.id} className={selected===c.id?"selected":""} onClick={()=>setSelected(c.id)}><Feed camera={c}/><span className="camera-meta"><b>{c.name}</b><small>{c.signal}% signal · {c.battery}% battery</small></span></button>)}</section><aside className="inspector"><header><div><h2>{camera.name}</h2><p>{camera.model}</p></div><Status value={camera.health}/></header><div className="control-list">{(Object.keys(camera.controls) as CameraControl[]).map(key=>{const item=camera.controls[key];return <label key={key}><span><b>{labels[key]}</b><em className={`command ${item.state}`}>{stateLabel[item.state]}</em></span>{typeof item.value==="boolean"?<input type="checkbox" checked={item.value} disabled={item.state==="unsupported"} onChange={e=>adapter.setCameraControl(camera.id,key,e.target.checked)}/>:<input aria-label={labels[key]} value={String(item.value)} disabled={item.state==="unsupported"} onChange={e=>adapter.setCameraControl(camera.id,key,e.target.value)}/>} {item.detail?<small>{item.detail}</small>:null}</label>})}</div></aside></div></main>}
function AudioPage({state,adapter}:{state:ReturnType<typeof useStudio>;adapter:StudioAdapter}){return <main><Header title="Audio" subtitle="Phone microphones stay independent until explicitly routed"/><div className="notice"><ShieldAlert/><span><b>No automatic mix</b><small>Select each source intentionally. Solo is monitoring-only.</small></span></div><section className="mixer" aria-label="Phone microphone mixer">{state.audio.map(a=><article key={a.id}><header><span><AudioLines/><b>{a.name}</b></span><Status value={a.health}/></header><Meter level={a.level}/><div className="db">{a.level} dBFS <span>{a.syncMs>0?"+":""}{a.syncMs} ms sync</span></div><label>Gain <input type="range" min="-24" max="12" value={a.gain} onChange={e=>adapter.setAudio(a.cameraId,{gain:Number(e.target.value)})}/><output>{a.gain} dB</output></label><div className="audio-buttons"><Button variant={a.muted?"destructive":"outline"} onClick={()=>adapter.setAudio(a.cameraId,{muted:!a.muted})}>Mute</Button><Button variant={a.solo?"default":"outline"} onClick={()=>adapter.setAudio(a.cameraId,{solo:!a.solo})}>Solo monitor</Button></div><label className="route"><input type="checkbox" checked={a.routed} onChange={e=>adapter.setAudio(a.cameraId,{routed:e.target.checked})}/><span><b>Route to Program</b><small>{a.routed?"Explicitly included":"Not included"}</small></span></label></article>)}</section></main>}
function Studio({state,adapter}:{state:ReturnType<typeof useStudio>;adapter:StudioAdapter}){const p=state.cameras.find(c=>c.id===state.programId)!;const pv=state.cameras.find(c=>c.id===state.previewId)!;return <main className="studio"><Header title="Studio" subtitle="Live multiview and engine-owned edit decisions" actions={<Button variant="outline" onClick={()=>adapter.simulateProgramFailure()}><CircleAlert/>Simulate live failure</Button>}/><AlertRail alerts={state.alerts.filter(a=>a.severity==="critical")} onGo={()=>{}}/><section className="program-row"><div><label>PROGRAM</label><Feed camera={p}/></div><div><label>PREVIEW</label><Feed camera={pv}/></div></section><section className="switcher"><div className="multiview">{state.cameras.map(c=><button key={c.id} aria-pressed={c.id===state.previewId} onClick={()=>adapter.selectPreview(c.id)}><Feed camera={c} compact/><span>{c.tally==="program"?"ON AIR":c.tally==="preview"?"NEXT":"SELECT"}</span></button>)}</div><div className="take"><Button size="lg" onClick={()=>adapter.take("cut")}>CUT <kbd>Space</kbd></Button><Button size="lg" variant="outline" onClick={()=>adapter.take("dissolve")}>DISSOLVE <kbd>D</kbd></Button></div></section><section className="studio-foot"><Panel title="Program audio"><div className="audio-summary">{state.audio.filter(a=>a.routed).map(a=><div key={a.id}><AudioLines/><b>{a.name}</b><Meter level={a.level}/></div>)}</div></Panel><Panel title="Outputs"><div className="output-lines"><span>ISO recording <Status value={state.output.recording?"ready":"offline"}/></span><span>Virtual camera <Status value={state.output.virtualCamera}/></span><span>OBS adapter <Status value={state.output.obs}/></span></div></Panel></section></main>}

export function App({adapter:provided}:{adapter?:StudioAdapter}){const adapter=useMemo(()=>provided??new DeterministicStudioAdapter(),[provided]);const state=useStudio(adapter);const [route,setRoute]=useState<Route>(()=>(location.hash.slice(2) as Route)||"dashboard");const navigate=(next:Route)=>{location.hash=`/${next}`;setRoute(next)};useEffect(()=>{const handler=(e:KeyboardEvent)=>{if(e.target instanceof Element&&e.target.matches("input,textarea,select"))return;if(e.key===" "){e.preventDefault();adapter.take("cut")}if(e.key.toLowerCase()==="d")adapter.take("dissolve");if(e.altKey&&/[1-4]/.test(e.key))navigate(routes[Number(e.key)-1].id)};window.addEventListener("keydown",handler);return()=>window.removeEventListener("keydown",handler)},[adapter]);return <div className="app-shell"><a className="skip" href="#content">Skip to content</a><aside className="nav"><div className="brand"><Radio/><span><b>OpenStream</b><small>STUDIO</small></span></div><nav>{routes.map(r=><button key={r.id} aria-current={route===r.id?"page":undefined} onClick={()=>navigate(r.id)}><r.icon/><span>{r.label}</span><kbd>Alt {routes.indexOf(r)+1}</kbd></button>)}</nav><div className="nav-foot"><Status value={state.readiness.engine} label="Engine connected"/><button onClick={()=>adapter.reset()}><RotateCcw/>Reset simulator</button><button><Settings2/>Settings</button></div></aside><div className="workspace"><div className="topbar"><span><Activity/> LIVE SESSION 01:42:18</span><span>4 phones · 1080p30</span><Status value={state.output.recording?"ready":"offline"} label={state.output.recording?"REC ISO":"Not recording"}/></div><div id="content">{route==="dashboard"?<Dashboard state={state} onGo={navigate}/>:route==="cameras"?<Cameras state={state} adapter={adapter}/>:route==="audio"?<AudioPage state={state} adapter={adapter}/>:<Studio state={state} adapter={adapter}/>}</div></div></div>}
export default App
